# 01 Data Cleaning

This notebook prepares the experimental AWGC datasets for machine-learning analysis.

The workflow includes:

- Loading raw phase-composition datasets
- Merging initial phase composition with SBF phase evolution
- Creating engineered features
- Saving a processed dataset for machine learning

In [1]:
import pandas as pd
from pathlib import Path

ROOT_DIR = Path('..')
RAW_DATA_DIR = ROOT_DIR / 'data' / 'raw'
PROCESSED_DATA_DIR = ROOT_DIR / 'data' / 'processed'

initial_path = RAW_DATA_DIR / 'initial_phase_composition.csv'
sbf_path = RAW_DATA_DIR / 'sbf_phase_evolution.csv'

initial_df = pd.read_csv(initial_path)
sbf_df = pd.read_csv(sbf_path)

initial_df.head(), sbf_df.head()

(   temperature_C  amorphous_pct  wollastonite_pct  hydroxyapatite_pct  \
 0            700           52.2              4.00               35.80
 1            800           59.6             10.10                6.73
 2            900           36.0              9.60               22.40
 3           1000           30.8             14.42               20.18
 4           1100           22.6             21.67               12.38

    whitlockite_pct
 0             8.00
 1            23.57
 2            32.00
 3            34.60
 4            43.34  ,
    temperature_C  soaking_day  amorphous_pct  wollastonite_pct  \
 0            700            3           47.8              4.75
 1            700            5           49.3              4.60
 2            700            7           40.1              5.45
 3            700           14           39.6              5.49
 4            700           21           44.6              5.04

    hydroxyapatite_pct  whitlockite_pct
 0               37.96             9.49
 1               36.87             9.23
 2               43.56            10.89
 3               43.92            10.98
 4               40.29            10.07  )

## Rename Columns

The initial and SBF datasets contain similar phase names. To avoid confusion after merging, the columns are renamed with `initial_` and `sbf_` prefixes.

In [2]:
initial_df = initial_df.rename(columns={
    'amorphous_pct': 'initial_amorphous_pct',
    'wollastonite_pct': 'initial_wollastonite_pct',
    'hydroxyapatite_pct': 'initial_hydroxyapatite_pct',
    'whitlockite_pct': 'initial_whitlockite_pct'
})

sbf_df = sbf_df.rename(columns={
    'amorphous_pct': 'sbf_amorphous_pct',
    'wollastonite_pct': 'sbf_wollastonite_pct',
    'hydroxyapatite_pct': 'sbf_hydroxyapatite_pct',
    'whitlockite_pct': 'sbf_whitlockite_pct'
})

initial_df.head(), sbf_df.head()

(   temperature_C  initial_amorphous_pct  initial_wollastonite_pct  \
 0            700                   52.2                      4.00
 1            800                   59.6                     10.10
 2            900                   36.0                      9.60
 3           1000                   30.8                     14.42
 4           1100                   22.6                     21.67

    initial_hydroxyapatite_pct  initial_whitlockite_pct
 0                       35.80                     8.00
 1                        6.73                    23.57
 2                       22.40                    32.00
 3                       20.18                    34.60
 4                       12.38                    43.34  ,
    temperature_C  soaking_day  sbf_amorphous_pct  sbf_wollastonite_pct  \
 0            700            3               47.8                  4.75
 1            700            5               49.3                  4.60
 2            700            7               40.1                  5.45
 3            700           14               39.6                  5.49
 4            700           21               44.6                  5.04

    sbf_hydroxyapatite_pct  sbf_whitlockite_pct
 0                   37.96                 9.49
 1                   36.87                 9.23
 2                   43.56                10.89
 3                   43.92                10.98
 4                   40.29                10.07  )

## Merge Datasets

The initial phase-composition dataset is merged with the SBF phase-evolution dataset using sintering temperature as the common variable.

In [3]:
ml_df = sbf_df.merge(initial_df, on='temperature_C', how='left')

ml_df.head()

,temperature_C,soaking_day,sbf_amorphous_pct,sbf_wollastonite_pct,sbf_hydroxyapatite_pct,sbf_whitlockite_pct,initial_amorphous_pct,initial_wollastonite_pct,initial_hydroxyapatite_pct,initial_whitlockite_pct
0,700,3,47.8,4.75,37.96,9.49,52.2,4.0,35.8,8.0
1,700,5,49.3,4.60,36.87,9.23,52.2,4.0,35.8,8.0
2,700,7,40.1,5.45,43.56,10.89,52.2,4.0,35.8,8.0
3,700,14,39.6,5.49,43.92,10.98,52.2,4.0,35.8,8.0
4,700,21,44.6,5.04,40.29,10.07,52.2,4.0,35.8,8.0

## Feature Engineering

New features are created to support interpretable machine-learning analysis.

In [4]:
ml_df['initial_crystallinity_pct'] = 100 - ml_df['initial_amorphous_pct']
ml_df['sbf_crystallinity_pct'] = 100 - ml_df['sbf_amorphous_pct']

ml_df['hydroxyapatite_gain_pct'] = (
    ml_df['sbf_hydroxyapatite_pct'] - ml_df['initial_hydroxyapatite_pct']
)

ml_df['wollastonite_change_pct'] = (
    ml_df['sbf_wollastonite_pct'] - ml_df['initial_wollastonite_pct']
)

ml_df.head()

,temperature_C,soaking_day,sbf_amorphous_pct,sbf_wollastonite_pct,sbf_hydroxyapatite_pct,sbf_whitlockite_pct,initial_amorphous_pct,initial_wollastonite_pct,initial_hydroxyapatite_pct,initial_whitlockite_pct,initial_crystallinity_pct,sbf_crystallinity_pct,hydroxyapatite_gain_pct,wollastonite_change_pct
0,700,3,47.8,4.75,37.96,9.49,52.2,4.0,35.8,8.0,47.8,52.2,2.16,0.75
1,700,5,49.3,4.60,36.87,9.23,52.2,4.0,35.8,8.0,47.8,50.7,1.07,0.60
2,700,7,40.1,5.45,43.56,10.89,52.2,4.0,35.8,8.0,47.8,59.9,7.76,1.45
3,700,14,39.6,5.49,43.92,10.98,52.2,4.0,35.8,8.0,47.8,60.4,8.12,1.49
4,700,21,44.6,5.04,40.29,10.07,52.2,4.0,35.8,8.0,47.8,55.4,4.49,1.04

## Save Processed Dataset

The final processed dataset is saved to `data/processed/awgc_ml_dataset.csv`.

In [5]:
PROCESSED_DATA_DIR.mkdir(parents=True, exist_ok=True)

output_path = PROCESSED_DATA_DIR / 'awgc_ml_dataset.csv'
ml_df.to_csv(output_path, index=False)

output_path

PosixPath('../data/processed/awgc_ml_dataset.csv')

## Kinetic Blueprint Context

The processed dataset generated in this notebook forms the foundation for subsequent exploratory, predictive, and bioactivity-oriented analyses.

The resulting dataset supports investigation of relationships among:

- Thermal processing
- Phase architecture
- Phase evolution
- Transport behavior
- Bioactivity-related outcomes

These relationships collectively contribute to the Kinetic Blueprint framework for deterministic materials design.